/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class splash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(splash.class.getName());

    /**427761219
     * Creates new form splash
     */
    public splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel_Loading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(102, 204, 0));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 613, 830, 28));

        jLabel_Loading.setFont(new java.awt.Font("Algerian", 1, 35)); // NOI18N
        jLabel_Loading.setForeground(new java.awt.Color(0, 204, 0));
        jLabel_Loading.setText("Loading.......");
        getContentPane().add(jLabel_Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 550, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home,,,,,.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel (NetBeans default code) */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // Error handling...
        }

        // --- KOODII SPLASH SCREEN AS IRRAA EEGALA ---
        
        // 1. Object uumuu
        splash sp = new splash();
        sp.setVisible(true); // Splash agarsiisi
        
        try {
            // 2. Loop 0 hanga 100 deemuu
            for (int i = 0; i <= 100; i++) {
                // Saffisa (Speed) isaa murteessuu (100ms = suuta, 20ms = dafee)
                Thread.sleep(40); 
                
                // 3. Percent agarsiisuu
                sp.jProgressBar1.setValue(i);
                
                // Barreeffama jijjiiruu (Optional)
                if(i == 10) sp.jLabel_Loading.setText("Turning On Modules...");
                if(i == 20) sp.jLabel_Loading.setText("Loading Database...");
                if(i == 50) sp.jLabel_Loading.setText("Connecting to Server...");
                if(i == 70) sp.jLabel_Loading.setText("Connection Successful...");
                if(i == 80) sp.jLabel_Loading.setText("Launching Application...");
                
                // 4. Yeroo 100 ga'u, Splash cufii Index bani
                if (i == 100) {
                    sp.setVisible(false);
                    new index().setVisible(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Loading;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
